# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/mood
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true

# Mail — fill in your credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giorgos95x@gmail.com
spring.mail.password=gupa ognj nqap ezgo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.base-url=http://localhost:3000
